name: tresto_v002a
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  equatable: ^2.0.5
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.4
  flutter_inappwebview: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.0.0
  flutter_native_splash: ^2.4.0
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  heroicons: ^0.10.0
  http: ^1.2.1
  logger: ^2.2.0
  meta: ^1.11.0
  webview_flutter: ^4.7.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#ffffff"
  image: "assets/download2.png"
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/download2.png"
  min_sdk_android: 21